### PR TITLE
Fix intensity normalizations

### PR DESCRIPTION
**Pull request by qin-yu**
Hi @carsen-stringer!

During the process of packaging the custom Cellpose model for bioimage.io, I identified two potential issues with the intensity normalization implementation in Cellpose. This PR proposes fixes for:

1. The current normalization with the `lowhigh` argument is not channel-wise. In this PR, `lowhigh` now either takes a 2-tuple `(low, high)` for all channels, or a `nchan`-tuple of that for each channel.
2. The current invert mechanism does not necessarily invert the channel to be segmented (`--chan`); instead, it inverts the last channel. Depending on the `--chan2` value, this might not be the intended channel. In this PR, all channels are inverted if `invert`.

<details>

<summary>Original PR message on 25 Jul 2024</summary>

## Original PR

Hi @carsen-stringer!

During the process of packaging the custom Cellpose model for bioimage.io, I identified two potential issues with the intensity normalization implementation in Cellpose. This PR proposes fixes for:

1. The current min-max normalization with the `lowhigh` argument is not channel-wise, and the argument itself might be misused.
2. The current invert mechanism does not necessarily invert the channel to be segmented (`--chan`); instead, it inverts the last channel. Depending on the `--chan2` value, this might not be the intended channel.

Please review these changes as I might have misunderstood some parts.

----

### Fix for Min-Max Normalization by 31bc5befb3573f9dd0cc46db392788fe32c96bcd

For `cellpose.transforms.normalize_img()` (channel-wise normalization), the `lowhigh` option is provided. I assume this corresponds to min-max normalization where `lowhigh` is a tuple representing (new minimum, new maximum).
https://github.com/MouseLand/cellpose/blob/84344b0ceb6eb91e759301fbdad5c9b77a1c881b/cellpose/transforms.py#L600-L601

If `lowhigh` represents (old minimum, old maximum), then normalization is not channel-wise if `lowhigh` has a length of 2:
https://github.com/MouseLand/cellpose/blob/84344b0ceb6eb91e759301fbdad5c9b77a1c881b/cellpose/transforms.py#L624-L626

In either case, the implementation needs fixing:
https://github.com/MouseLand/cellpose/blob/84344b0ceb6eb91e759301fbdad5c9b77a1c881b/cellpose/transforms.py#L640-L643
The current implementation is essentially: `img_norm = (img_norm - lowhigh[0]) / (lowhigh[1] - lowhigh[0])`

This has been fixed by commit 31bc5befb3573f9dd0cc46db392788fe32c96bcd.

----

### Fix for Invert by 91469d1273ee0b3e3e4f614d0e8a80b0587ceb40

For `cellpose.transforms.normalize_img()` (channel-wise normalization), there is an `invert` option for cases where "cells are dark instead of bright":
https://github.com/MouseLand/cellpose/blob/84344b0ceb6eb91e759301fbdad5c9b77a1c881b/cellpose/transforms.py#L598-L599

In Cellpose, the invert function is performed after `reshape()`, which moves the main channel to channel 0 and the auxiliary channel to channel 1. Therefore, the primary use case is to invert the first channel (channel 0) instead of the last one (current implementation):
https://github.com/MouseLand/cellpose/blob/84344b0ceb6eb91e759301fbdad5c9b77a1c881b/cellpose/transforms.py#L666-L667

The variable `c` retains the value from a previous loop, being 1 if `nchan` is 2 or 2 if `nchan` is 3.

This has been fixed by commit 91469d1273ee0b3e3e4f614d0e8a80b0587ceb40, but further improvements can be made to allow for a user-specified list of channels to be inverted.

</details>

### CODE REVIEW

**Comment by carsen-stringer** [comment]
thanks @qin-yu ! the lowhigh is meant to represent the values to set to 0 and 1 (e.g. pixel value 100->0 and 1100->1 corresponds to lowhigh = [100,1100]. I think the fix here would be to check if lowhigh is a list of lists (per channel) or a single list (for all channels). It's a good point that this use-case isn't covered currently.

for the inversion, thanks for catching that, I think it would make sense to apply for all channels?

**Comment by qin-yu** [comment]
> thanks @qin-yu ! the lowhigh is meant to represent the values to set to 0 and 1 (e.g. pixel value 100->0 and 1100->1 corresponds to lowhigh = [100,1100]. I think the fix here would be to check if lowhigh is a list of lists (per channel) or a single list (for all channels). It's a good point that this use-case isn't covered currently.

Thanks for explaining! That makes sense, working on it.

> for the inversion, thanks for catching that, I think it would make sense to apply for all channels?

Yes you are right, inverting all channels by default if `invert == True` seems natural to me. But maybe this could also be either a `bool` or `tuple(bool, ...)`?

**Comment by carsen-stringer** [comment]
Thanks so much, regarding the invert function I think it's fine with all channels, I'm not sure how much it's being used with multichannel images

**Comment by qin-yu** [comment]
> Thanks so much, regarding the invert function I think it's fine with all channels, I'm not sure how much it's being used with multichannel images

You are right. Let's keep it simple

I have finalized the PR, including two fixes along with the corresponding tests. Please take a look when you have a moment! @carsen-stringer

**Comment by qin-yu** [comment]
The failed check seems to be incidental and maybe unrelated to the PR.

**Pull request merged**
