### PR TITLE
Delete multiple ROIs in GUI

### PR DESCRIPTION
**Pull request by mrariden**
### Add functionality to GUI to allow 'batch' deletion of masks:

Current implementation is a button that starts batch deletion mode and masks can be selected/deselected until pressing the 'done' button. Once the 'done' button is pressed, the masks are removed from the relevant state variables and the mask is saved once. 

### Task list: 
- [x] Add button(s) to start/stop batch deletion mode
- [x] Add function(s) to connect buttons
- [x] Allow region selection of multiple ROIs
- [x] ~~Write tests?~~
- [x] Write documentation with images (maybe video?)
- [ ] User testing on 
    - [x] Linux
    - [x] Windows
    - [ ] Mac
 - [x] Test with 3d image stack 
 - [x] Verify that `manual` tags are properly updated

### Addresses:
- #703 
- #501

### CODE REVIEW

**Comment by mrariden** [comment]
Buttons now working. When button is clicked, the user can select masks (currently by individually clicking, but will implement region selection) and delete the selected masks with the done button.

Before:
image

Selection:
image

After deletion:
image

**Comment by mrariden** [comment]
All test look good, just need final testing on Mac & Windows.

**Comment by mrariden** [comment]
@LeireIglesiasC This feature is not currently merged into the main branch of cellpose, and that's why you don't see it. For the moment you can speed up deleting cells by disabling autosaving the _seg.npy file (File drop down -> Disable autosave checkbox). You will need to update your cellpose version since this feature was only added last week. You can do that with:

`conda activate cellpose` Activate your environment, assuming you called it cellpose
`pip install cellpose==2.2.3`



_Or_ you can install this version of cellpose (the delete multiple feature) with these commands:

`conda activate cellpose` Activate your environment, assuming you called it cellpose
`pip install git+https://github.com/mrariden/cellpose.git@delete_multiple_roi`

If you do the latter please let us know your experience using the delete multiple feature!

**Comment by LeireIglesiasC** [comment]
Hi @mrariden , Thank you very much for your fast response. I tried both options you gave, the first one works perfectly! I updated the cellpose version and without the automatic saving the whole process is much faster. 
I tried the second option just in case, but since it gave an error after running the command, so I have not used the delete multiple ROIs feature yet sorry.
image

Leire

**Comment by mrariden** [comment]
Ah this merge broke the disable autosave feature by replacing the `save_sets_with_check()` with the original `save_sets()`

**Pull request merged**
