### PR TITLE
OpenVINO backend

### PR DESCRIPTION
**Pull request by dkurt**
same as https://github.com/MouseLand/cellpose/pull/370 but in contrib

Efficiency measured on https://drive.google.com/open?id=18syVlaix8cIlrnNF20pEWKMWUsKx9R9z (16 images):
```
python -m cellpose --dir cellpose_test --pretrained_model cyto --chan 2 --chan2 3 --verbose
```
| Backend | Processing time |
| ---|---|
| PyTorch 1.11.0 (mkldnn) | 94.808 sec |
| OpenVINO 2021.3 | 56.975 sec |

CPU: `Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz`

### CODE REVIEW

**Comment by dkurt** [comment]
Hi, @carsen-stringer and @kevinjohncutler! This PR proposes OpenVINO in contrib.

**Comment by carsen-stringer** [comment]
hey @dkurt I started testing this on windows and it seems I need to install visual studio in the default instructions. is there a conda version of the package we could use? I'm not sure if a 2x speed up is worth the hassle of this sort of install, unless there's a large improvement of speed in the training time. this is the error I got with only pip installing openvino==2021.3:
```
Traceback:
..\..\anaconda3\envs\cp\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\contrib\test_openvino.py:5: in <module>
    from cellpose.contrib import openvino_utils
cellpose\contrib\openvino_utils.py:5: in <module>
    from openvino.inference_engine import IECore
..\..\anaconda3\envs\cp\lib\site-packages\openvino\inference_engine\__init__.py:34: in <module>
    from .ie_api import *
E   ImportError: DLL load failed while importing ie_api: The specified module could not be found.
```

**Comment by dkurt** [comment]
@carsen-stringer, thanks for pointing this issue! Just tried Anaconda environment and done necessary changes. Please note that it required change install approach: from `pip install cellpose[openvino]` to just `pip install --no-deps openvino` because of NumPy conflict.

**Comment by carsen-stringer** [comment]
thanks! I'm getting the 2x speed up now! Is there any way to add the parameters method to the openvino model so we can use it with training? this is the error I get when trying to train a model with openvino:
```
AttributeError                            Traceback (most recent call last)
Input In [25], in <cell line: 15>()
     12 output = io.load_train_test_data(train_dir, test_dir, mask_filter='_seg.npy')
     13 train_data, train_labels, _, test_data, test_labels, _ = output
---> 15 new_model_path = model.train(train_data, train_labels, 
     16                               test_data=test_data,
     17                               test_labels=test_labels,
     18                               channels=channels, 
     19                               save_path=train_dir, 
     20                               n_epochs=100,
     21                               learning_rate=0.1, 
     22                               weight_decay=0.0001, 
     23                               nimg_per_epoch=8,
     24                               model_name='CP_tissuenet')
     26 # diameter of labels in training images
     27 diam_labels = model.diam_labels.copy()

File c:\users\csmp\github\cellpose\cellpose\models.py:783, in CellposeModel.train(self, train_data, train_labels, train_files, test_data, test_labels, test_files, channels, normalize, save_path, save_every, save_each, learning_rate, n_epochs, momentum, SGD, weight_decay, batch_size, nimg_per_epoch, rescale, min_train_masks, model_name)
    781 if channels is None:
    782     models_logger.warning('channels is set to None, input must therefore have nchan channels (default is 2)')
--> 783 model_path = self._train_net(train_data, train_flows, 
    784                              test_data=test_data, test_labels=test_flows,
    785                              save_path=save_path, save_every=save_every, save_each=save_each,
    786                              learning_rate=learning_rate, n_epochs=n_epochs, 
    787                              momentum=momentum, weight_decay=weight_decay, 
    788                              SGD=SGD, batch_size=batch_size, nimg_per_epoch=nimg_per_epoch, 
    789                              rescale=rescale, model_name=model_name)
    790 self.pretrained_model = model_path
    791 return model_path

File c:\users\csmp\github\cellpose\cellpose\core.py:802, in UnetModel._train_net(self, train_data, train_labels, test_data, test_labels, save_path, save_every, save_each, learning_rate, n_epochs, momentum, weight_decay, SGD, batch_size, nimg_per_epoch, rescale, model_name)
    799     self.learning_rate = LR
    801 self.batch_size = batch_size
--> 802 self._set_optimizer(self.learning_rate[0], momentum, weight_decay, SGD)
    803 self._set_criterion()
    805 nimg = len(train_data)

File c:\users\csmp\github\cellpose\cellpose\core.py:749, in UnetModel._set_optimizer(self, learning_rate, momentum, weight_decay, SGD)
    747 def _set_optimizer(self, learning_rate, momentum, weight_decay, SGD=False):
    748     if SGD:
--> 749         self.optimizer = torch.optim.SGD(self.net.parameters(), lr=learning_rate,
    750                                     momentum=momentum, weight_decay=weight_decay)
    751     else:
    752         import torch_optimizer as optim # for RADAM optimizer

AttributeError: 'OpenVINOModel' object has no attribute 'parameters'
```

**Comment by dkurt** [comment]
@carsen-stringer, OpenVINO can be used only for inference time, not training.

**Comment by carsen-stringer** [comment]
I see okay thanks!

**Pull request merged**
