### PR TITLE
Fix for issue #380

### PR DESCRIPTION
**Pull request by pascal-pfeiffer**
* omni arg was missing for tests label flow generation

### CODE REVIEW

**Comment by pascal-pfeiffer** [comment]
Fix for issue #380

**Comment by authman** [comment]
Nice catch Ilu. Maybe consider also adding in the other missing params as well `use_gpu` and `device` in addition to `omni`.

**Comment by CozyDoomer** [comment]
@pascal-pfeiffer are you still working on this?
I could add the 2 missing parameters as well since I also ran into this bug.

Would make sense to me to merge this soon since I've seen it pop up everytime someone tried to train omnipose models with a test set

**Comment by pascal-pfeiffer** [comment]
Added the other two params.
Should be good to merge.

**Comment by carsen-stringer** [comment]
thanks this has been fixed

**Pull request closed without merging**
