### PR TITLE
set the masks uint variable type dynamically

### PR DESCRIPTION
**Pull request by elmbeech**
Hi there! 

This is the second try to resolve issue #283 pull request #284 .
I introduced some dynamical variable typing to set the masks uint type.

Elmar

### CODE REVIEW

**Comment by yfukai** [comment]
Thank you @elmbeech for this pull request! I could not take time to resolve conflicts in my original issue after major update, and I think your new attempt is helpful.
I think one potential problem with dynamical `dtype` would be the computational cost of `masks.max() ` itself. I'd rather stick to static `dtype`, but for dynamical `dtype` options, I think there should be an option to disable this feature. Maybe we can ask for an opinion of @carsen-stringer on this...

**Comment by elmbeech** [comment]
Hi @yfukai, I not at all insist on that dynamical variable typing implementation. 
If your changes were good enough, but were just conflicting with the major update, then I can simply re-submit your changes.
The only thing I aim for is, that the 32uint issue is resolved in the main branch.
Whatever @carsen-stringer think is need, I can try to do.  Elmar

**Comment by carsen-stringer** [comment]
unfortunately we use cv2 for resizing (does not take uint32) so this change breaks more downstream code. I've modified the typing inside the compute_masks function to take care of that now and tested with a 9000x9000 image with 80000 cells. check out the master branch to try it

**Comment by elmbeech** [comment]
Thank you, @carsen-stringer for taking care of the issue and solved the problem!
Thrilled that cellpose compute_masks now can handle more than 2**16 cells.

**Pull request closed without merging**
